#!/usr/bin/env bash
# Configure domain ./1-world_wide_web <domain> <subdomain>
# Shellcheck disable.

subdomain () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 2 ]
then
  subdomain "$1" "$2"
else
  subdomain "www.$1" www
  subdomain "lb-01.$1" lb-01
  subdomain "web-01.$1" web-01
  subdomain "web-02.$1" web-02
fi
