#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a response

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me/https://www.youtube.com/watch?
v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a error_page 404 /404.html;location = 404.html {root /var/www/html; internal;}'
/etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By ${170658-web-02};"
/etc/nginx/sites-available/default
service nginx start
