#!/usr/bin/env bash
# installs HAPROXY and setups load balancer
sudo apt-get update
sudo apt-get -y install haproxy

# Load balancer's configuration
DOMAIN_NAME='trekgroup.tech'


printf "\n frontend $DOMAIN_NAME-frontend
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 170658-web-01 18.214.87.1
    server 170658-web-02 100.26.215.237" >> /etc/haproxy/haproxy.cfg
service haproxy start
