#!/usr/bin/env bash
# Configure Nginx to listen to Port 80

rm /etc/nginx/sites-enabled/defult
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
